// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdeohzwzfclzklrjacey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZW9oend6ZmNsemtscmphY2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MTkxMzUsImV4cCI6MjA1Mzk5NTEzNX0.rzlOVPfZzl2dpbkOvZ78X-3q2BgVIj5T6SE28Fn1GoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);